name: Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install mdBook and preprocessors
        run: |
          # Install mdBook
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          sudo mv mdbook /usr/local/bin/
          
          # Install mdbook-mermaid
          curl -L https://github.com/badboy/mdbook-mermaid/releases/download/v0.12.6/mdbook-mermaid-v0.12.6-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          sudo mv mdbook-mermaid /usr/local/bin/
          
          # Install mdbook-toc
          curl -L https://github.com/badboy/mdbook-toc/releases/download/0.14.1/mdbook-toc-0.14.1-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          sudo mv mdbook-toc /usr/local/bin/
      
      - name: Build documentation
        run: mdbook build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'book/book'
      
      - name: Deploy Preview
        if: github.ref != 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
      
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        id: production
        uses: actions/deploy-pages@v4 